apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      run: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        run: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.11
        ports:
        - containerPort: 9042
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cassandra
#   labels:
#     run: cassandra
# spec:
#   ports:
#   - port: 9042
#     protocol: TCP
#   selector:
#     run: cassandra